language: node_js
node_js:
  - "6"
services:
  - mongodb
before_script:
  - npm run seedData
script:
  - npm test
after_success:
  - npm install codeclimate-test-reporter -g
  - npm run coverage
addons:
    code_climate:
        repo_token: ead35028c1aa8e823031641917e4fd04337cb87481636edf97bcb1f4cd6a1771